import 'package:flutter/material.dart';

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  background: Colors.black,
  onBackground: Colors.black,
  primary: Colors.black,
  onPrimary: Colors.black,
  primaryContainer: Colors.black,
  onPrimaryContainer: Colors.black,
  secondary: Colors.black,
  onSecondary: Colors.black,
  secondaryContainer: Colors.black,
  onSecondaryContainer: Colors.black,
  tertiary: Colors.black,
  onTertiary: Colors.black,
  tertiaryContainer: Colors.black,
  onTertiaryContainer: Colors.black,
  error: Colors.black,
  onError: Colors.black,
  errorContainer: Colors.black,
  onErrorContainer: Colors.black,
  surface: Colors.black,
  onSurface: Colors.black,
  inverseSurface: Colors.black,
  onInverseSurface: Colors.black,
  surfaceTint: Colors.black,
  surfaceVariant: Colors.black,
  onSurfaceVariant: Colors.black,
  outline: Colors.black,
  outlineVariant: Colors.black,
  inversePrimary: Colors.black,
  shadow: Colors.black,
  scrim: Colors.black,
);
